### ISSUE TITLE
React manual valiadtion warnings

### ISSUE THREAD

**Issue by bijoutrouvaille** [react-materialize/webpack-boilplate#4]
Fresh install from github results in this warning printed 12 times in the chrome console,

bundle.js:21627 Warning: You are manually calling a React.PropTypes validation function for the `onChange` prop on `Input`. This is deprecated and will not work in the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.

I've updated react-materialize, react and react-dom versions to what's in the main repository and the warnings went away.

**Comment by alextrastero** [comment]
Please reopen if this is still happening as of today
